dist: build
builds:
  - main: ./cmd/webapi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -H windowsgui
    binary: 'webapi'
    goos:
      - windows
      - linux
    goarch:
      - amd64
#    hooks:
#      post: 'upx --brute build/webapi-dav_{{ .Env.GOOS }}_{{ .Env.GOARCH }}/*'

archive:
  replacements:
    386: i386
  name_template: '{{ .Binary }}-{{ .Os }}'
  files:
    - config.toml
    - static/*
    - orario.xml

release:
  name_template: '{{ .Version }}'
  github:
    owner: Baldomo
    name: webapi-dav
  draft: true
  disable: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-{{ .Commit }}-next'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
