# Configurazione esempio in TOML

[generali]
# TODO
riavvio_automatico = true
index_html = "./static/index.html"
non_trovato_html = "./static/404.html"

[connessione]
porta = "8080"
apache_cgi = false

[cartelle]
comunicati_genitori = "./comunicati-genitori"
comunicati_studenti = "./comunicati-studenti"
comunicati_docenti = "./comunicati-docenti"
# TODO
progetti = "./progetti"

[logging]
log_in_terminale = true
salva_su_file = false
file_log = "./webapi.log"
# Può essere "verbose", "warning" o "error"
livello_log = "verbose"