[generali]
riavvio_automatico = true  # TODO: da implementare

[https]
abilitato = false
porta = ":443"
certificato = "server.crt"
chiave = "id_rsa.nodes"

[http]
abilitato = true
porta = ":8080"

[cartelle]
html = "static"
comunicati_genitori = "comunicati-genitori"
comunicati_studenti = "comunicati-studenti"
comunicati_docenti = "comunicati-docenti"
progetti = "progetti"  # TODO: da implementare

[logging]
log_in_terminale = true
salva_su_file = false
file_log = "webapi.log"
livello_log = "verbose"