[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/radovskyb/watcher"
  version = "1.0.2"

[[constraint]]
  name = "github.com/appleboy/go-fcm"
  version = "0.1.1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/nightlyone/lockfile"


[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"
